# Generated by Django 4.0.5 on 2022-07-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='کاربر روپومدا', max_length=250, verbose_name='Name'),
        ),
    ]
