# Generated by Django 3.2 on 2022-07-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_general', models.BooleanField(default=False)),
                ('gift_code_type', models.IntegerField(choices=[(0, 'PERCENT_BASE'), (1, 'PRICE_BASE')])),
            ],
            options={
                'verbose_name': 'Gift Code',
                'verbose_name_plural': 'Gift Codes',
            },
        ),
    ]
