# Generated by Django 3.2 on 2022-08-02 16:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('description', models.TextField(blank=True, default='خرید از وبسایت روپومدا', max_length=200, null=True)),
                ('authority', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.IntegerField(choices=[(0, 'INITIATED'), (1, 'PENDING'), (2, 'SUCCESS'), (4, 'CANCELED'), (5, 'FAILED')], default=0)),
                ('payment_method', models.IntegerField(choices=[(0, 'ZARRIN_PAL'), (1, 'COD')])),
                ('ref_id', models.TextField(blank=True, max_length=250, null=True)),
                ('is_payed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
