# Generated by Django 3.2 on 2022-07-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20220728_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
