# Generated by Django 3.2 on 2022-07-28 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20220728_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='count',
            new_name='quantity',
        ),
    ]
