# Generated by Django 3.2 on 2022-07-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20220728_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='cart',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
