# Generated by Django 4.0.5 on 2022-07-08 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_mobile_is_verified_user_mobile_verified'),
        ('store_management', '0005_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'INITIATED'), (1, 'ACCEPTED_PROCESSING'), (2, 'DELIVERED_POSTOFFICE'), (3, 'DELIVERY_AGENT_SENT')])),
                ('payment_method', models.IntegerField(choices=[(0, 'ZARRIN_PAL'), (1, 'COD')])),
                ('payment_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_management.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_management.product')),
            ],
            options={
                'verbose_name': 'OrderRow',
                'verbose_name_plural': 'OrderRows',
            },
        ),
    ]
