# Generated by Django 4.0.5 on 2022-07-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0006_order_orderrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
