# Generated by Django 3.2 on 2022-07-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_collection_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
