# Generated by Django 3.2 on 2022-07-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220727_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='post_code',
            field=models.CharField(max_length=20),
        ),
    ]
