# Generated by Django 3.2 on 2022-07-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
