apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: django
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      name: django
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        app: django
        name: django
    spec:
      containers:
        - image: mormoroth/django:shop
          imagePullPolicy: Always
          env:
            - name: DB_NAME
              value: djangotest
            - name: DB_USER
              value: root
            - name: DB_PASS
              value: djangotest
            - name: DB_HOST
              value: postgresql-svc
            - name: DB_PORT
              value: '5432'
            - name: DB_SCHEMA
              value: public
          name: django
          command:
            - python
            - manage.py
            - runserver
            - '0.0.0.0:8000'
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              ephemeral-storage: 2G
              memory: 1G
            requests:
              cpu: '1'
              ephemeral-storage: 2G
              memory: 1G
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
