# Generated by Django 3.2 on 2022-07-30 17:30

from django.db import migrations, models
import django.db.models.deletion
import store.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        ('category', '0001_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('code', models.IntegerField(db_index=True, default=100000)),
                ('title_fa', models.CharField(max_length=300)),
                ('title_en', models.CharField(default='', max_length=300)),
                ('slug', models.CharField(max_length=350, unique=True)),
                ('rrp_price', models.IntegerField(default=0)),
                ('selling_price', models.IntegerField(default=0)),
                ('inventory', models.IntegerField(default=0)),
                ('max_quantity', models.IntegerField(default=1)),
                ('is_promotion', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('main_image', models.ImageField(upload_to=store.utils.product_main_image_path, verbose_name='main image')),
                ('active_collection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.collection')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='category.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='seller.seller')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title_fa', models.CharField(default='تصویر محصول', max_length=300)),
                ('title_en', models.CharField(default='product image', max_length=300)),
                ('url', models.ImageField(upload_to=store.utils.product_image_path, verbose_name='image')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='store.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
