# Generated by Django 3.2 on 2022-07-23 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.AutoField(default=602940, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=350, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('image', models.ImageField(upload_to='uploads/products/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
