# Generated by Django 3.2 on 2022-08-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_color_size_variety'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variety',
            options={'verbose_name_plural': 'Varieties'},
        ),
    ]
