# Generated by Django 3.2 on 2022-07-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220723_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title_en',
            field=models.CharField(default='', max_length=300),
        ),
    ]
