# Generated by Django 3.2 on 2022-08-03 15:35

from django.db import migrations, models
import django.db.models.deletion
import store.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_variety_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarietyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title_fa', models.CharField(default='تصویر محصول', max_length=300)),
                ('title_en', models.CharField(default='product image', max_length=300)),
                ('url', models.ImageField(upload_to=store.utils.product_image_path, verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rrp_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='variety',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variety',
            name='max_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='variety',
            name='rrp_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variety',
            name='selling_price',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.AddField(
            model_name='varietyimage',
            name='variety',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='store.variety'),
        ),
    ]
