# Generated by Django 3.2 on 2022-08-03 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('store', '0004_auto_20220803_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variety',
            old_name='Size',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variety',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variety',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='seller.seller'),
        ),
    ]
