# Generated by Django 3.2 on 2022-08-05 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('store', '0005_auto_20220803_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='seller.seller'),
        ),
    ]
