# Generated by Django 3.2 on 2022-07-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.AutoField(auto_created=True, db_index=True, default=602940, primary_key=True, serialize=False, unique=True),
        ),
    ]
