# Generated by Django 3.2 on 2022-07-26 13:58

from django.db import migrations, models
import store.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.IntegerField(db_index=True, default=100000),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=store.utils.product_image_path),
        ),
    ]
