# Generated by Django 3.2 on 2022-07-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20220726_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='uuid',
            new_name='id',
        ),
    ]
