# Generated by Django 3.2 on 2022-07-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20220727_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='inventory',
        ),
        migrations.AddField(
            model_name='product',
            name='max_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
