# Generated by Django 3.2 on 2022-07-29 02:26

from django.db import migrations, models
import django.db.models.deletion
import store.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20220726_1520'),
        ('seller', '0009_auto_20220728_2340'),
        ('store', '0019_auto_20220728_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='', upload_to=store.utils.product_image_path, verbose_name='main image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='category.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='seller.seller'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_fa', models.CharField(max_length=300)),
                ('title_en', models.CharField(default='', max_length=300)),
                ('url', models.ImageField(upload_to=store.utils.product_image_path, verbose_name='image')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='store.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
