# Generated by Django 3.2 on 2022-07-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20220729_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='title_en',
            field=models.CharField(default='product image', max_length=300),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='title_fa',
            field=models.CharField(default='تصویر محصول', max_length=300),
        ),
    ]
