# Generated by Django 4.0.5 on 2022-06-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='auth_code',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile_is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
