# Generated by Django 4.0.5 on 2022-07-07 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_phone_number_user_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mobile_is_verified',
            new_name='mobile_verified',
        ),
    ]
