# Generated by Django 3.2 on 2022-07-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_alter_notice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
