# Generated by Django 3.2 on 2022-07-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20220728_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='notice',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
