# Generated by Django 3.2 on 2022-07-26 15:55

from django.db import migrations, models
import django.db.models.deletion
import seller.utils


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_is_active'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='name',
        ),
        migrations.AddField(
            model_name='seller',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=seller.utils.seller_logo_path),
        ),
    ]
