# Generated by Django 3.2 on 2022-07-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20220726_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='store_name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
