# Generated by Django 3.2 on 2022-07-26 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_seller_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
