# Generated by Django 3.2 on 2022-07-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_auto_20220728_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
