# Generated by Django 3.2 on 2022-07-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_seller_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='seller',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
    ]
