# Generated by Django 3.2 on 2022-08-02 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_payed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='billing.payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'INITIATED'), (3, 'ACCEPTED_PROCESSING'), (6, 'DELIVERED_POSTOFFICE'), (9, 'DELIVERY_POSTMAN'), (11, 'DELIVERY_CUSTOMER'), (12, 'CANCELED_BY_USER'), (13, 'CANCELED_BY_SELLER'), (14, 'CANCELED_BY_ADMIN')], default=0),
        ),
    ]
