# Generated by Django 3.2 on 2022-07-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrow',
            name='product',
        ),
    ]
