# Generated by Django 3.2 on 2022-08-05 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_variety_seller'),
        ('order', '0003_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrow',
            name='product',
        ),
        migrations.AddField(
            model_name='orderrow',
            name='variety',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.variety'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(-3, 'CANCELED_BY_ADMIN'), (-2, 'CANCELED_BY_SELLER'), (-1, 'CANCELED_BY_USER'), (0, 'INITIATED'), (1, 'REGISTERED'), (2, 'PROCESSING'), (6, 'DELIVERED_POSTOFFICE'), (9, 'DELIVERY_POSTMAN'), (11, 'DELIVERY_CUSTOMER')], default=0),
        ),
    ]
