# Generated by Django 3.2 on 2022-07-27 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_address_post_code'),
        ('order', '0004_auto_20220726_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.address'),
            preserve_default=False,
        ),
    ]
