# Generated by Django 3.2 on 2022-07-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderrow',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
