# Generated by Django 3.2 on 2022-07-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20220728_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'INITIATED'), (1, 'ACCEPTED_PROCESSING'), (2, 'DELIVERED_POSTOFFICE'), (3, 'DELIVERY_AGENT_SENT'), (4, 'DELIVERY_CUSTOMER')], default=0),
        ),
    ]
