# Generated by Django 3.2 on 2022-07-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20220729_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrow',
            old_name='count',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'INITIATED'), (3, 'ACCEPTED_PROCESSING'), (6, 'DELIVERED_POSTOFFICE'), (9, 'DELIVERY_AGENT_SENT'), (11, 'DELIVERY_CUSTOMER'), (12, 'CANCELED_BY_USER'), (13, 'CANCELED_BY_SELLER'), (14, 'CANCELED_BY_SELLER')], default=0),
        ),
    ]
